Questions in SubCommand_Create.java
Ghost-chu/QuickShop-Reremake pull request #1017
Opened 2021-06-04 13:51 UTC by Chris6ix

1.What exactly is meant by "3rd-plugin-build-check-failed"? (line 130)
2.What is this "Util" (line 147)

2021-06-10 11:43 UTC, Ghost-chu commented on src/main/java/org/maxgamer/quickshop/command/subcommand/SubCommand_Create.java
> +                    MsgUtil.sendMessage(p, MsgUtil.getMessage("->3rd-plugin-build-check-failed", p, result.getMessage()));
This is a string key and points to a language file string, you shouldn't touch it.

2021-06-10 11:43 UTC, Ghost-chu commented on src/main/java/org/maxgamer/quickshop/command/subcommand/SubCommand_Create.java
> +                Util.debugLog("->Util report you can't build shop there.");
Ignore it, it's debug log

2021-06-10 11:43 UTC, Ghost-chu requested changes
There something that needs to pay attention to.

2021-06-11 16:27 UTC, Chris6ix commented
okay

2021-06-11 16:27 UTC, closed without merging