Load tax account just once
Ghost-chu/QuickShop-Reremake pull request #1077
Opened 2021-06-11 16:49 UTC by PaulBGD

We found that the OfflinePlayer lookup here could stall the main thread on networking, as each time it would have to retrieve data about the player from Mojang. This PR loads the OfflinePlayer just once when the configuration is loaded, and keeps it cached.

2021-06-11 16:53 UTC, Ghost-chu commented
it has been cached here: https://github.com/Ghost-chu/QuickShop-Reremake/blob/03b47a8bee01d23b88a33cf2aec823a87890bb70/src/main/java/org/maxgamer/quickshop/shop/ShopManager.java#L68
try use it

2021-06-11 17:03 UTC, Ghost-chu requested changes
use ShopManager.cacheTaxAccount

2021-06-11 17:03 UTC, Ghost-chu commented on src/main/java/org/maxgamer/quickshop/QuickShop.java
> +        this.taxAccount = this.getServer().getOfflinePlayer(
use ShopManager.cacheTaxAccount

2021-06-11 22:16 UTC, gp-Airee commented
@Ghost-chu this is a fairly large issue, +1

2021-06-12 00:42 UTC, Ghost-chu approved these changes

2021-06-12 03:56 UTC, merged