5.0.0.12
Ghost-chu/QuickShop-Reremake pull request #1585
Opened 2021-11-10 08:38 UTC by Ghost-chu

2021-11-10 09:09 UTC, sandtechnology requested changes

2021-11-10 09:11 UTC, Ghost-chu commented on src/main/java/org/maxgamer/quickshop/util/matcher/item/BukkitItemMatcherImpl.java
> +        }
/minecraft:give @s minecraft:stone{shopItemId:"test"} to create a stone with test shopItemId
/minecraft:give @s minecraft:dirt{shopItemId:"test"} to create a dirt with test shopItemId

2021-11-10 09:11 UTC, Ghost-chu commented on src/main/java/org/maxgamer/quickshop/util/matcher/item/BukkitItemMatcherImpl.java
> +        }
/minecraft:give @s minecraft:stone{shopItemId:"test"} to create a stone with test shopItemId
/minecraft:give @s minecraft:dirt{shopItemId:"test"} to create a dirt with test shopItemId

2021-11-13 08:54 UTC, merged

2021-11-14 15:26 UTC, sandtechnology commented on src/main/java/org/maxgamer/quickshop/integration/advancedregionmarket/AdvancedShopRegionMarketIntegration.java
> +        Set<Chunk> chuckLocations = new HashSet<Chunk>();
Vector maxPoint = region.getRegion().getMinPoint() is wrong

2021-11-14 15:26 UTC, sandtechnology commented on src/main/java/org/maxgamer/quickshop/integration/advancedregionmarket/AdvancedShopRegionMarketIntegration.java
> +                Shop shop = shopMap.get(shopLocation);
Still wrong revert commit